### ISSUE TITLE
Navbar mobile view width not full

### ISSUE THREAD

**Issue by Nithin-Valiyaveedu** [Uyadav207/denkMinds#46]
![image](https://github.com/user-attachments/assets/292e910e-d866-4f80-a7f9-98516339934a)

**Comment by Sindhura492** [comment]
<img width="633" alt="Screenshot 2024-11-03 at 4 24 29 AM" src="https://github.com/user-attachments/assets/ba965e85-cc63-4eea-ba3b-54c7c39cad73">
